### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by paultag** [Debian/ud#17]
Looks like ud is still using the Deprecated Django 1.4 `execute_manager`, which was removed in 1.8

```python
(ud)[tag@cassiel:~/dev/local/ud][⎇  paultag/feature/setup] ♥  ud
Traceback (most recent call last):
  File "/home/tag/.virtualenvs/ud/bin/ud", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tag/dev/local/ud/src/ud", line 4, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
```

**Comment by paultag** [comment]
This kicked up a massive fun nest of errors including multiple objects pulling from the same class, which causes two fields with the same name on the MRO to break Django.

This is actually fun. I'm taking this bug. MINE.

**Comment by tfheen** [comment]
I started going down the rabbit hole with @paultag on this, fixing the immediate execute_manager problem is a matter of just:

```--- a/src/ud
+++ b/src/ud
@@ -1,7 +1,10 @@
-#!/usr/bin/env python
-import os
-import sys
-from django.core.management import execute_manager
-from ud import settings
-sys.path.append(os.path.dirname(os.path.realpath(settings.__file__)))
-execute_manager(settings)
+#! /usr/bin/env python
+
+import os, sys
+
+if __name__ == "__main__":
+        os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ud.settings")
+        
+        from django.core.management import execute_from_command_line
+
+        execute_from_command_line(sys.argv)
```

however, this runs into weird problems with the MRO as @paultag mentioned, and trying to hack around those is non-trivial, it seems.
